[package]
name = "toupcam-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = ">=0.34, <0.36"
bayer = "0.1.5"
toupcam = { version = "0.1", path = "../toupcam" }
